name: Vinifera Wines and Ales
favicon: null
layout_spectrum: 0.70358
typography_spectrum: 0.8349743476137519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#591e00'
    - '#ae9600'
    - '#c5b4a8'
    - '#aa5d7c'
  brandStrength: 0.47110377601347864
  lightness: 0.640440751099959
  saturation: 0.375
  rhythmicContrast: 0.607561360578984
purpose: []
